[phases.setup]
nixPkgs = ["python311Full", "python311Packages.pip", "gcc"]

[phases.install]
cmds = ["python -m pip --break-system-packages install -r backend/requirements.txt"]

[phases.start]
cmd = "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
