[phases.setup]
nixPkgs = ["python311Full", "gcc"]

[phases.install]
cmds = ["python -m ensurepip", "python -m pip install -r backend/requirements.txt"]

[phases.start]
cmd = "cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
